### ISSUE TITLE
CatalogExportApi autogeneration

### ISSUE THREAD

**Issue by magento-engcom-team** [magento/catalog-storefront#430]
### Description

Autogenerated **CatalogExportApi* classes must be placed into *generated** folder.

**AC**:
* classes must be generated into /**generated*` folder and has the same structure CatalogExportApi/Api/Data/**
* logic with classes generation moved to /**Setup/Recurring.php**
* existing command **bin/magento dto:generate**`eliminated

**Comment by magento-engcom-team** [comment]
The issue was exported from the internal JIRA. The link to the original JIRA issue: https://jira.corp.magento.com/browse/SFAPP-140

**Comment by bricht** [comment]
@magento I am working on this

**Comment by bricht** [comment]
setup:di:compile does not work with this currently, because it does not regenerate our DTOS.
-No way to get around deletion of the files I think. \Magento\Setup\Console\CompilerPreparation::handleCompilerEnvironment deletes the whole generated folder.

-If we do the following then it works.
Add our generator class here
\Magento\Setup\Module\Di\App\Task\OperationFactory::$operationsDefinitions
Add our generator class here
\Magento\Setup\Console\Command\DiCompileCommand::getOperationsConfiguration

Obviously move the generator logic out of Rrecurring.php and into another class which can be reused from lets say
\Magento\Setup\Module\Di\App\Task\Operation\DtoGenerator (new class) which checks whether the ExportApiModule exists at all. Or we pass params to it.

Either way seems like we currently need to modify Task\OperationFactory and Command\DiCompileCommand

**Comment by bricht** [comment]
Or maybe we could move the configuration for compiling in di.xml and add a custom step to collect this configuration, make it extendable. But not 100% sure if this is viable.
